service: authorization-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin


provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1

functions:
  basicAuthorizer:
    handler: handlers/basicAuthorizer.handler
    events:
      - http:
          path: /import
          method: get
          cors: true
